# Generated by Django 4.2.14 on 2024-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basemodel",
            name="description",
            field=models.TextField(default="Demo"),
        ),
    ]
